### ISSUE TITLE
how to train the model

### ISSUE THREAD

**Issue by aicha0910** [anuragkr90/weak_feature_extractor#5]
As your paper says，the audio has different length,so,how can i do to train the model ？
thank you and your work is amazing!

**Comment by anuragkr90** [comment]
you dont need to do anything. The network is designed to handle recordings of variable. So you can train the network as it is. In pytorch, do the usual 

```optimizer.zero_grad() 
batch_pred = net(input) 
batch_train_loss = loss_fn(batch_pred,lbdata)
batch_train_loss.backward()
optimizer.step()```

**Comment by aicha0910** [comment]
the question is how to creat a batch.because the audio has different length.if i use dataloader .it can't stack different shape of the feature.     thank you very much!
发自网易邮箱 iPhone 版
On 04/16/2019 13:05, Anurag Kumar wrote:

you dont need to do anything. The network is designed to handle recordings of variable. So you can train the network as it is. In pytorch, do the usual

optimizer.zero_grad() batch_pred = net(input) batch_train_loss = loss_fn(batch_pred,lbdata) batch_train_loss.backward() optimizer.step()

**Comment by anuragkr90** [comment]
You can create sets of the data by appending data (zeros or repeating audio) and then do minibatch training over each set. For example, map all audios of length between from 4.5 seconds to 5 seconds to 5 seconds and so on. For audioset, most of the recordings are already 10 seconds, so that will be one set.  Those which are not can be mapped into 10-15 other sets. 

You can do this at logmel feature level as well by appending frames. This is what I had done.

**Comment by aicha0910** [comment]
Thanks for your reply！
This is exactly what I want!
